<?php
namespace Company\EventzBundle\Repository;

/**
 * WantedTicketRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WantedTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
